name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # כל תג שמתחיל ב־v

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Deploy to Production
        run: |
          echo "Deploying to Production..."
          # פה תוכל להוסיף את הפקודות להפצת קוד ל־Production (למשל, Docker, SSH, Heroku) 